import { CheckCircle2, FileCode2, LoaderCircle, MoveRight, TriangleAlert } from "lucide-react";

import type { NimbusBrowserState, NimbusWorkItem } from "@/app/nimbus-api";

function Evidence({ path, startLine, endLine, role, onOpen }: { path: string; startLine: number; endLine: number; role: string; onOpen: () => void }): React.JSX.Element { return <button type="button" className="nimbus-evidence" onClick={onOpen}><FileCode2 /><span>{path}:{startLine}-{endLine}</span><em>{role}</em></button>; }
export function ImplementationView({ workItem, browser, onOpenCodex }: { workItem: NimbusWorkItem; browser: NimbusBrowserState; onOpenCodex: () => void }): React.JSX.Element {
  const items = workItem.plan?.items ?? [];
  return <section className="nimbus-implementation" data-testid="implementation-surface"><header><div><span className="nimbus-kicker"><MoveRight /> Plan to implementation</span><h2>What actually happened</h2><p>Each completed plan item receives one evidence-backed implementation result.</p></div></header><ol>{items.map((item) => { const result = workItem.implementation.find((candidate) => candidate.planItemId === item.id); const active = browser.activePlanItemId === item.id; return <li key={item.id} className={active ? "is-active" : result !== undefined ? "is-complete" : ""}><div className="nimbus-implementation-marker">{active ? <LoaderCircle className="animate-spin" /> : result ? <CheckCircle2 /> : <span />}</div><div className="nimbus-implementation-copy"><div><span>{item.id}</span><h3>{item.title}</h3></div><p>{item.outcome}</p>{active ? <div className="nimbus-loading"><LoaderCircle className="animate-spin" /> {browser.activityPhrase ?? "Working through this plan item"}</div> : null}{result ? <div className="nimbus-result"><strong>{result.id}</strong><p>{result.actualResult}</p>{result.deviation ? <p className="nimbus-deviation"><TriangleAlert /> Deviation: {result.deviation}</p> : null}<div>{result.evidence.map((evidence) => <Evidence key={`${evidence.path}-${evidence.startLine}`} {...evidence} onOpen={onOpenCodex} />)}</div></div> : null}</div></li>; })}</ol></section>;
}
