import { Check, CircleAlert, FileSearch, Search, Wrench } from "lucide-react";
import { useState } from "react";

import type { NimbusWorkItem } from "@/app/nimbus-api";
import { Button } from "@/components/ui/button";

export function ReviewView({ workItem, onAccept, onInvestigate, onCorrection }: { workItem: NimbusWorkItem; onAccept: () => void; onInvestigate: () => void; onCorrection: (correction: string) => void }): React.JSX.Element {
  const [correction, setCorrection] = useState(""); const missing = (workItem.plan?.items ?? []).filter((item) => !workItem.implementation.some((result) => result.planItemId === item.id)); const deviations = workItem.implementation.filter((result) => result.deviation !== null);
  return <section className="nimbus-review" data-testid="review-surface"><header><span className="nimbus-kicker"><FileSearch /> Derived review</span><h2>Reconcile intent with reality</h2><p>Review is a derived lens. It highlights exceptions instead of copying the Work Item into another artifact.</p></header><div className="nimbus-review-grid"><article><h3><CircleAlert /> Exceptions</h3>{missing.length === 0 && deviations.length === 0 ? <p className="nimbus-clear"><Check /> No missing mappings or deviations are currently recorded.</p> : <ul>{missing.map((item) => <li key={item.id}><strong>{item.id}</strong> has no implementation result.</li>)}{deviations.map((result) => <li key={result.id}><strong>{result.id}</strong> deviated: {result.deviation}</li>)}</ul>}</article><article><h3><Search /> Investigations</h3>{workItem.investigations.length > 0 ? <ul>{workItem.investigations.map((item) => <li key={item.taskId}>{item.conclusion}</li>)}</ul> : <p>No published investigations.</p>}</article><article><h3><Wrench /> Mental model changes</h3><p>{deviations.length === 0 ? "No model changes were inferred from the recorded implementation." : "Deviations above should be treated as changes to the expected mental model."}</p></article></div><footer><Button variant="outline" onClick={onInvestigate}><Search data-icon="inline-start" /> Investigate</Button><input value={correction} onChange={(event) => setCorrection(event.target.value)} placeholder="Describe an implementation correction" /><Button variant="outline" onClick={() => { if (correction.trim()) onCorrection(correction.trim()); }} disabled={correction.trim().length === 0}><Wrench data-icon="inline-start" /> Request correction</Button><Button onClick={onAccept}><Check data-icon="inline-start" /> Accept review</Button></footer></section>;
}
